sudo: required

before_cache:
- rm -rf /home/travis/.cargo/registry

cache:
  directories:
  - /home/travis/.cargo

git:
  depth: 1

addons:
  apt:
    packages:
      - libasound2-dev

matrix:
  include:
    # Linux
    - os: linux
      language: rust
      rust: stable
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy --tests -- -D warnings
        - cargo build

    # OSX
    - os: osx
      language: rust
      rust: stable
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy --tests -- -D warnings
        - cargo build

    # Windows
    - os: windows
      language: rust
      rust: stable
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy --tests -- -D warnings
        - cargo build

