[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
getopts = "0.2.21"
glutin = "0.25.1"
image = "0.23.12"
luminance = "0.43.1"
luminance-gl = "0.16.1"
luminance-derive = "0.6.3"
luminance-glutin = "0.11.2"

[profile.release]
debug = true
