[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
crossterm = "0.22.1"
getopts = "0.2.21"
glutin = "0.27"
luminance = "0.44.0"
luminance-gl = "0.17.0"
luminance-derive = "0.7.0"
luminance-glutin = "0.12.0"
rodio = "0.14.0"

[dependencies.image]
version = "0.23.14"
default-features = false


[profile.release]
debug = true
