[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
getopts = "0.2.21"
image = "0.22.3"
luminance = "0.37.1"
luminance-derive = "0.5"
luminance-glutin = "0.6"
termion = "1.5.4"
