[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitfield = "0.14.0"
crossterm = "0.26.1"
getopts = "0.2.21"
gilrs = "0.10.1"
glutin = { version = "0.28", default-features = false }
luminance = "0.46.0"
luminance-gl = "0.19.1"
luminance-derive = "0.9.0"
luminance-glutin = "0.14.1"
rodio = "0.17.1"

[dependencies.image]
version = "0.24.3"
default-features = false

[profile.release]
debug = true
