[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
getopts = "0.2.21"
glutin = "0.27"
image = "0.23.14"
luminance = "0.44.0"
luminance-gl = "0.17.0"
luminance-derive = "0.7.0"
luminance-glutin = "0.12.0"

[profile.release]
debug = true
