[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
crossterm = "0.23.0"
getopts = "0.2.21"
gilrs = "0.8.2"
glutin = "0.28.0"
luminance = "0.46.0"
luminance-gl = "0.19.0"
luminance-derive = "0.9.0"
luminance-glutin = "0.14.0"
rodio = "0.15.0"

[dependencies.image]
version = "0.24.0"
default-features = false


[profile.release]
debug = true
